import React from "react";
import Head from "next/head";

import Layout from "../../src/layout/Layout";
import ImageProjectsBlock from "../../src/blocks/ImageProjectsBlock";
import { graphicDesign } from "../../public/data/projectsData";


export default function Home() {
    return (
        <>
            <Head>
                <title>Create Kurac App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=" text-white">
                <Layout>
                    <ImageProjectsBlock {...graphicDesign}/>
                    <></>                    
                </Layout>
            </main>
        </>
    );
}